In [1]:
print("jaymin")

jaymin


In [2]:
j=print("wohoo")
j

wohoo


In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c=np.zeros(2)
print(c)

[0. 0.]


In [8]:
c1=np.zeros(3)
print(c1)

[0. 0. 0.]


In [9]:
c2=np.zeros(8)
print(c2)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
c3=np.zeros((3,4))
print(c3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
import numpy as np

In [3]:
c4=np.zeros((3,2,4))
print(c4)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
c5=np.zeros((6,1,3))
print(c5)

[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]


In [6]:
import numpy as np

In [7]:
c6=np.full((3,2),2)
print(c6)

[[2 2]
 [2 2]
 [2 2]]


In [8]:
c7=np.full((2,4),9)
print(c7)

[[9 9 9 9]
 [9 9 9 9]]


In [9]:
d=np.array([(1,2,3,4,5,6)])
np.random.rand(3,5)
print(d)

[[1 2 3 4 5 6]]


In [12]:
print(np.random.rand(3,5))

[[0.37751302 0.28393328 0.41692621 0.89354436 0.87911681]
 [0.81602948 0.03524834 0.04973075 0.15465779 0.57057248]
 [0.91875367 0.77206222 0.63643499 0.23543609 0.1307558 ]]


In [14]:
print(np.random.rand(9,6))

[[0.07001786 0.58167853 0.8422377  0.42815391 0.28297524 0.86855656]
 [0.3822542  0.34314639 0.28001603 0.39422775 0.13377435 0.87991485]
 [0.46523851 0.20905181 0.64118508 0.14923736 0.28929423 0.4999907 ]
 [0.38308697 0.39565284 0.79263316 0.78889454 0.73904752 0.8848015 ]
 [0.95499236 0.95123135 0.17428552 0.82515929 0.25521934 0.60566237]
 [0.21095236 0.28846696 0.32957165 0.54182587 0.6525389  0.47037793]
 [0.85881813 0.38481608 0.21311312 0.61726366 0.61170121 0.02088601]
 [0.17613786 0.76190597 0.70264091 0.30265037 0.76223751 0.59327501]
 [0.69381145 0.07351376 0.10179655 0.09386645 0.54373216 0.62979817]]


In [15]:
e=np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
e1=np.eye(4)
print(e1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
e2=np.eye(9)
print(e2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
e3=np.copy(e1)
print(e3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
e3.view()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
d.view()

array([[1, 2, 3, 4, 5, 6]])

In [34]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [35]:
a.view()

array([1, 2, 3, 4, 5, 6])

In [36]:
c5=a.reshape(2,-1)
print(c5)

[[1 2 3]
 [4 5 6]]


In [38]:
c6=a.reshape(3,-1)
print(c6)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
f=np.array([2,9,6,1,7])
f

array([2, 9, 6, 1, 7])

In [52]:
g=f.sort()
print(g)

None


In [54]:
c1=np.array([[1,7,4],[5,8,6]])
c1.sort(axis=1)
c1

array([[1, 4, 7],
       [5, 6, 8]])

In [56]:
c1=np.array([[9,4,5,2],[5,8,6,1]])
c1.sort(axis=0)
c1

array([[5, 4, 5, 1],
       [9, 8, 6, 2]])

In [57]:
a.view()

array([1, 2, 3, 4, 5, 6])

In [59]:
z=np.delete(a,2)
z

array([1, 2, 4, 5, 6])

In [60]:
k=np.random.rand(3,5)
print(k)

[[0.22798841 0.61454152 0.49608378 0.1511525  0.28847376]
 [0.3620838  0.70017778 0.26124219 0.35188652 0.28135695]
 [0.95166666 0.84546727 0.96501278 0.59884306 0.14325112]]


In [61]:
k1=k.reshape(5,-1)
print(k1)

[[0.22798841 0.61454152 0.49608378]
 [0.1511525  0.28847376 0.3620838 ]
 [0.70017778 0.26124219 0.35188652]
 [0.28135695 0.95166666 0.84546727]
 [0.96501278 0.59884306 0.14325112]]


In [62]:
k.view()

array([[0.22798841, 0.61454152, 0.49608378, 0.1511525 , 0.28847376],
       [0.3620838 , 0.70017778, 0.26124219, 0.35188652, 0.28135695],
       [0.95166666, 0.84546727, 0.96501278, 0.59884306, 0.14325112]])

In [66]:
k2=np.delete(k,2)
k2

array([0.1511525 , 0.22798841, 0.26124219, 0.49608378, 0.61454152,
       0.28135695, 0.35188652, 0.3620838 , 0.14325112, 0.59884306,
       0.70017778, 0.84546727, 0.95166666, 0.96501278])

In [67]:
k3=np.delete(k,9)
print(k3)

[0.1511525  0.22798841 0.28847376 0.26124219 0.49608378 0.61454152
 0.28135695 0.35188652 0.3620838  0.59884306 0.70017778 0.84546727
 0.95166666 0.96501278]


In [1]:
import numpy as np

In [2]:
i=np.array([1,4,9,2,5])
print(i)

[1 4 9 2 5]


In [11]:
i1=np.append([1,2,3],5)
print(i1)

[1 2 3 5]


In [12]:
i2=np.insert([1,2,3,8,7],4,9)
print(i2)

[1 2 3 8 9 7]


In [13]:
i3=np.insert([1,3,8,7],2,4)
print(i3)

[1 3 4 8 7]


In [1]:
import numpy as np

In [3]:
np.delete([1,9,7,5,4],2,axis=0)

array([1, 9, 5, 4])

In [8]:
g1=np.delete([[1,9,4,20],[2,5,6,10]],3,axis=1)
g1

array([[1, 9, 4],
       [2, 5, 6]])

In [14]:
g1=np.concatenate(([1,9,4,20],[2,5,6,10]),axis=0)
g1

array([ 1,  9,  4, 20,  2,  5,  6, 10])

In [24]:
b=np.array([(1,2,3),(4,5,6)])
print(b)
g1=np.concatenate((b),axis=0)
g1

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [25]:
b=np.array([(1,2,3),(4,5,6)])
print(b)
g1=np.concatenate((b),axis=1)
g1

[[1 2 3]
 [4 5 6]]


AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
g3=np.split([1,9,8,4],2)
g3

AttributeError: 'list' object has no attribute 'shape'

In [29]:
a=np.array([1,9,7,5,2,3])
a

array([1, 9, 7, 5, 2, 3])

In [30]:
a[0]

1

In [42]:
a=np.array([[1,9,7,5,2,3],[11,16,13,15,17,12]])
a


array([[ 1,  9,  7,  5,  2,  3],
       [11, 16, 13, 15, 17, 12]])

In [39]:
a[2,3]=1

IndexError: index 2 is out of bounds for axis 0 with size 2

In [47]:
a=np.array([1,9,7,5,2,3])
a[2]


7

In [48]:
a=np.array([1,9,7,5,2,3])
a[0:4]

array([1, 9, 7, 5])

In [49]:
a=np.array([1,9,7,5,2,3])
a[3,5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [50]:
a=np.array([1,9,7,5,2,3])
a[ :2]

array([1, 9])

In [52]:
a=np.add(5,6)
a

11

In [54]:
a=np.subtract(5,3)
a

2

In [57]:
a=np.multiply(5,3)
a

15

In [58]:
a=np.divide(5,3)
a

1.6666666666666667

In [59]:
a=np.exp(5)
a

148.4131591025766

In [60]:
a=np.sqrt(5)
a

2.23606797749979

In [61]:
a==b

array([[False, False, False],
       [False, False, False]])

In [62]:
np.array_equal(5,6)

False

In [63]:
9==10

False

In [67]:
a=np.array([1,9,8,7])
a.sum()


25

In [68]:
a=np.array([1,9,8,7])
a.min()

1

In [69]:
a=np.array([1,9,8,7])
a.max(axis=0)

9

In [70]:
a=np.array([1,9,8,7])
a.mean()

6.25

In [71]:
a=np.array([1,9,8,7])
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'